# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6af4af4d41bb1308eab816c30c1d28a04c2e2890bba859538c86d18a2e894000b2b6284139a719b55ce86976a97550c9cea97de786bcb55dd16bfd9f758aed5

test:
  secret_key_base: c9aecbe2c10f1c36c39bc3e89d9f9248c52697c5bc3869124b218ef2f69ee90102bd3875fa5e449c162786eefbad751f01022f317a0e975588b32a62af32b40e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
